DROP DATABASE IF EXISTS payment;
DROP USER IF EXISTS `payment_admin`@`localhost`;
CREATE DATABASE IF NOT EXISTS payment CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS `payment_admin`@`localhost` IDENTIFIED WITH mysql_native_password BY 'payment_pw';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, REFERENCES, INDEX, ALTER, EXECUTE, CREATE VIEW, SHOW VIEW,
CREATE ROUTINE, ALTER ROUTINE, EVENT, TRIGGER ON `payment`.* TO `payment_admin`@`localhost`;
FLUSH PRIVILEGES;