###
POST http://localhost:8080/api/v1/payment
Content-Type: application/json

{
  "payer_name": "John Green",
  "amount": 12.4
}

###
GET http://localhost:8080/api/v1/payment/find/id/20021b7c-2307-44cb-ad26-ef0fbbe556b5
Accept: application/json

###
